# Site settings
title: Dreaming Machines
tag_text: Dreaming Machines
description: A whole new way to think about art

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
